# Generated by Django 5.1 on 2024-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_month', models.CharField(max_length=7, unique=True)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food', models.DecimalField(decimal_places=2, max_digits=6)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone', models.DecimalField(decimal_places=2, max_digits=6)),
                ('electric', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trash', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mortgage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('child_care', models.DecimalField(decimal_places=2, max_digits=6)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
