# Generated by Django 5.1 on 2024-08-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_month',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
