# Generated by Django 5.1 on 2024-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cash', 'Cash'), ('Check', 'Check')], default='Credit Card', max_length=11),
        ),
    ]
