# Generated by Django 5.1 on 2024-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_month',
            field=models.CharField(choices=[('id', 'budget_month'), ('id', 'budget_month')], max_length=7),
        ),
    ]
