# Generated by Django 5.1 on 2024-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_expense_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_month',
            field=models.CharField(choices=[('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month'), ('id', 'budget_month')], max_length=7),
        ),
    ]
