# Generated by Django 5.1 on 2024-08-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_remove_expense_budget_month_expense_budget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2024-08-28'),
        ),
    ]
