# Generated by Django 5.1 on 2024-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_alter_expense_budget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2024-09-11'),
        ),
    ]
